### ISSUE TITLE
Extend test_access in `test_util.py` to include all methods defined in NamedList

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#106]
Each dunder method should be covered.

**Comment by bthayer2365** [comment]
@sahansk2 , since you wrote NamedList, can you write the tests?

**Comment by sahansk2** [comment]
Sure thing! I'll make a pull request for it.

**Comment by sahansk2** [comment]
Would you like me to write tests for the NamedList class itself, or would you like me to test NamedList class dunder methods through the child classes (Skill/AllSkills)?

**Comment by bthayer2365** [comment]
I figure you can just work off of what I've done since all_skills is an
instantiated implementation of it, and contains other instantiated
implementations (Skills). By testing these, you don't have to instantiate
your own object.

If you don't like that, you're free to do whatever else works for you.
