### ISSUE TITLE
Add a welcome message when git gud is first initialized

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#109]
Right now, it just says "Welcome to Git Gud.", but I would love if we had more information listed that directs users to this repo and explains the Git Gud commands commonly used.

**Comment by attard-andrew** [comment]
Hi,

Fairly new here. Would like to assist with this one.  I've jumped through the Repo a bit & cannot find where the string 'Welcome to Git Gud" is defined.  In a scenario such as this - is there an easy way for me to search within a Repo or otherwise find this bit of code other than asking or manually searching?

When it comes to the message explaining commands that are commonly used - I assume you are referring to the most commonly used Git Gud commands, but wanted to confirm since it could also be interpreted that you are referring to general Git commands (git add, git status, git commit etc.)

Thanks!

**Comment by bthayer2365** [comment]
Hi @attard-andrew,

If you haven't already, I'd recommend downloading an IDE like PyCharm (my favorite). It has functions to search for strings throughout all the files. In pycharm it's `Ctrl+Shift+F`. There's also ways to do it on the command line, but I prefer the IDE. 

The string you're looking for is in the code itself, in the `gitgud/__main__.py` file. This file is what's run when you type in `python -m gitgud` and the rest of the code executes from there. The structure is to have a bunch of different handlers that handle the different commands, and in this case, the command being handled is "init", and the handler is `handle_init`.

And yes, I meant the most commonly used Git Gud commands. Play through the levels and you can decide which those are. The levels themselves will teach the relevant git commands.

I'm looking forward to your contribution!

**Comment by attard-andrew** [comment]
I've been through a few levels and believe that I can at least identify the top 3-4 commands.  I'll try adding these to the welcome message.  I've been experiencing a number of other software & general usability issues which I'll document in another issue.
