### ISSUE TITLE
Git Gud Errors & Usability

### ISSUE THREAD

**Issue by attard-andrew** [benthayer/git-gud#112]
I've made it as far as the merge level.  Apologies if these issues have already been discussed - I checked the backlog but couldn't find anything (based on the summary field only).  I thought I would provide my honest feedback as a user, which I hope is interpreted as constructive criticism.

While some of these may seem obvious to someone that is comfortable with git & the command line - my assumption is that the target user is typically new to both (which - I am actually).

- Initial setup went smoothly. 
- The first set of instructions progress as the user hits enter. When I receive the instruction **"By running 'git gud commit', 'git gud' will automatically create a new file, add that file to the git index and commit it. Try it out!"** I did try it out - right then and there.  However, the instructions had not completed running and I didn't realize that running the command at this point would not actually register - it simply advanced the set of instructions 1 step further.  The instructions then proceeded until I arrived at the instruction **"Now, let's start using git!"**.  At this point I was confused - did I just complete the practice level?? I then ran 'git gud instructions' and found myself back at the start.  I eventually scrolled back up to the initial goal and executed 2 more 'git gud commit' commands before proceeding
- When running **'git gud test'** to check level completion - it works, but the following message is also displayed each time. I don't know enough to know what this means yet:

![image](https://user-images.githubusercontent.com/54812701/68749813-712a8e80-0631-11ea-8ddc-102aecf0aae0.png)

- On the next level, again found it confusing to receive step-by-step instructions to complete an action, while having to wait for all instructions to pass before being able to execute any of the taught commands. Regardless, I proceeded to complete the level, receiving the same error message shown in the image above both while using 'git gud commit' and 'git gud test'
- On the next level (basics merging), now aware of the quirks, I read through all instructions, the completed each command as instructed. When testing - it says that the level is not complete. I repeated the instructions multiple times to ensure there had not been an error or missed step on my part, and each time tested, but I am unable to complete the level

@bthayer2365

**Comment by bthayer2365** [comment]
Thank you @attard-andrew , this is very helpful!

We are currently in pre-release, so there are going to be many issues like this. My plan was to start more rigorous user-testing soon, so your comments are right on time and much appreciated.

First, the WinError 6 issue has actually already been addressed, but it's not on our end. The issue is with GitPython (https://github.com/gitpython-developers/GitPython/issues/935). I've fixed the issue in that repo, but the fix has not yet been pushed to pypi. I just asked if they could push the change. As you observed, the command still works. The issue occurs after all processes have run. My best understanding of the issue is that Windows realizes the subprocess we use for git operations is done before Python realizes it. Windows shuts it down for us, so when Python tries to shut down the process, the "handle" that is tries to use is now invalid.

For now, if you want to fix it locally, you can download the most current code and run.
```
git clone https://github.com/gitpython-developers/GitPython.git
cd GitPython
pip uninstall gitpython
pip install .
cd ../git-gud
pip install -e .
```


Now to address the issues with the levels:
For the first level, I just created a new pull request with some updates. Let me know what you think. #114
I did the same for the merging level, but since I'm not sure what your issue was, my changes might be irrelevant. This PR is #115

For merging, it will be helpful to see what commands you were entering. The correct sequence of commands for that level is 
```
git checkout -b bugFix
git gud commit
git checkout master
git gud commit
git merge bugFix
```
What did you enter? Was it something like:
```
git checkout -b bugFix
git gud commit
git checkout master
git checkout bugFix
git gud commit
git checkout master
git merge bugFix
```

**Comment by bthayer2365** [comment]
@attard-andrew I should probably mention that in order to test my code, you'll have to run the following commands:
```
git remote add ben https://github.com/bthayer2365/git-gud.git
git fetch ben
git checkout level1-clarity
```
Your code will be the same as my code on that branch you'll see the new output when running `git gud instructions`
