### ISSUE TITLE
Update asciinema

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#138]
Hey @sahansk2, once #134 is done, can you update the gif to include `git gud load next` instead of `git gud progress`

A couple other notes:
- Can you update it so that it doesn't include use of the instructions command? I think for the purposes of a demo, there's too much to read.
- Also go ahead and complete the first level right away since that's what the users will do
- Use `git gud load next` after the first level instead of after the second
- Show off a big level like extras octopus. This might scare people or get them excited, but I want to test it out and see how people perceive it
- Change the name of the file to preview.gif to make it a little more clean!
- Prepare to update this several times. You can add a file to save the commands so it's easy to look up the commands used for the demo in the future

The goal is to make sure other people can understand it, so throw in anything else that you think would help people understand what's going on. (Maybe slowing down in certain spots)

**Comment by sahansk2** [comment]
Sure -- I'm probably going to go about typing up a script that would automatically simulate keypresses at whatever speed would be good, just so that I can pipe it into asciinema whenever changes are to be made.

As an aftereffect, this initial update issue may take longer to resolve than future update issues regarding the demo.

**Comment by benthayer** [comment]
No problem, if it saves time and you learn something interesting, I'm all for it. No rush either way.
