### ISSUE TITLE
`git gud --help` error: "No manual entry for git-gud"

### ISSUE THREAD

**Issue by sahansk2** [benthayer/git-gud#244]
### Expected result
The output of `git gud --help` should either be the same as `git gud -h`, or it should open the man page for git-gud.

Output of `git gud -h`:
```
user@ubuntu:git-gud$ git gud --h
usage: git gud [-h] [--version] <command> ...

optional arguments:
  -h, --help    show this help message and exit
  --version     show program's version number and exit

Subcommands:
  <command>
    status      Print out the name of the current level
    explain     Show the explain for the current level
    goal        Concisely show what needs to be done to complete the level.
    reset       Reset the current level
    reload      Alias for reset
    test        Test to see if you've successfully completed the current level
    level       Display current level
    goal        Show a description of the current goal
    contributors
                Show project contributors webpage
    issues      Show project issues webpage
    help        Show help for commands
    solution    Show solution for the given level
    init        Init Git Gud and load first level
    load        Load a specific skill or level
    skills      List skills
    levels      List levels in a skill
    commit      Quickly create and commit a file
```
### Actual Behavior
Output of `git gud --help`:
```
user@ubuntu:git-gud$ git gud --help
No manual entry for git-gud
See 'man 7 undocumented' for help when manual pages are not available.
```
### Environment:
[Partial] output of `uname -a`:
```
Linux [redacted] 5.4.0-42-generic #46~18.04.1-Ubuntu SMP Fri Jul 10 07:21:24 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
python: `3.6.9`
git: `2.27.0`
git gud is installed with `pip3 install -e`, at commit b34dea1e324d8d6dbad784f9ad4e19aaeb7f9f25 on `master`

**Comment by benthayer** [comment]
You should be able to resolve the issue by installing without -e. We had this issue before where it seemed like the man page wasn't working, but it was really just the edit mode install that was having issues.

A couple other words though. `--help` seems to be handled by git while `-h` seems to be handled by git gud. With the man page present this should work

Modify line 28 of `__main__.py` to this see that git is processing `--help` for us (because `--help` still works)
```
28         self.parser = argparse.ArgumentParser(prog='git gud', add_help=False)
```
https://docs.python.org/3/library/argparse.html#argumentparser-objects

**Comment by benthayer** [comment]
This is good to be aware of, but I don't believe there is an issue here. Let me know if you disagree and we can continue this discussion
