### ISSUE TITLE
[possible bug] no git-gud for git-gud?

### ISSUE THREAD

**Issue by 429IhD0** [benthayer/git-gud#323]
I'm trying to git gud at git, and to that end I have installed git-gud.

I understand that in order to use git-gud to git gud at git, I must first git gud at git-gud. However, I was unable to locate any package or commands designed to help me git gud at git-gud specifically. 

Is this a bug or by design? I don't understand how I am supposed to git gud at git with git-gud without any help gitting gud at git-gud first.

**Comment by benthayer** [comment]
Glad you're in trying out my project! Git Gud --help should be useful. We are working on levels that introduce the git gud commands and so that when whole thing feels more natural. If you want to install the development version, it will be more up to date with those levels. Install instructions should be in the readme. Comment here with any feedback, I'm glad to have it 🙂
