### ISSUE TITLE
Keep track of commit hashes using a .json file

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#40]
We should keep track of the hashes of the commits we create using `git gud commit` and `git gud load`. Each one of these commits will a name, as defined in #34, but we should create a file, `.git/gud/commits.json` and store the hashes of the commits that we create. This will be useful for checking if the level is complete and validating what we think happened happened. The json should look like this:
```
{
'commit_name': 'hash'
...
}
```
Where the hash is what shows up when we run `git log` and `commit_name` is something like `C1`, `C2`, `M1`

Don't forget about Python's `json` module

**Comment by TSSlade** [comment]
I think I'd like to take this on. Just trying to get oriented to where the code would go. Presumably it's in `__main__.py`, but I skimmed through it and wasn't able to tell where the interception of the `git commit` would happen.

**Comment by bthayer2365** [comment]
You're right that it is in main. We actually have another issue open for disabling `git commit` in favor of `git gud commit` for most challenges. For this issue, the function to worry about is handle_commit, which should lead you to the right place. Since that's the main way to commit, we can just update all the hashes from there. There are other issues open to handle the situations of merging and rebasing (#41 and #43 respectively)

**Comment by bthayer2365** [comment]
Also, be sure to make use of the `Operator` class. All file operations that use the `.git/gud` directory should happen in `Operator`

**Comment by parkmichael777** [comment]
Hey @TSSlade, are you still working on this?

**Comment by benthayer** [comment]
If @TSSlade doesn't respond by Friday, @parkmichael777 has my permission to take over here
