### ISSUE TITLE
Store merge hashes

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#41]
Once we complete #40, we'll want to also keep track of the hashes of the merges. We'll also want to give them names like "M1", "M2", etc. as defined in #38. We can do this using the `post-merge` hook. See #40 for the details of the .json file. 

#38 is similar, but these two issues can be completed in any order.

This resource will be helpful:
https://git-scm.com/docs/githooks

**Comment by bthayer2365** [comment]
I'm not sure when this will be useful, so I'm going to close

**Comment by parkmichael777** [comment]
So I'm trying to understand how post-rewrite works so that I can do something similar for post-merge. So far, I understand that you have an array for all the hooks and when gitgud initalizes, it creates the post-rewrite hook and tells it to execute your python script. However, when I do git gud reset, and look for this hook_file (in my testing directory), I can't find it. Also, when I use git rebase, the stuff in your post-rewrite.py script doesn't print; instead, I see this:
"First, rewinding head to replay your work on top of it...
Applying:" 
Which I can't track down the location of (nothing shows up on grep).

**Comment by benthayer** [comment]
Delete the folder you're testing in and re-initialize. Look in main's
handle_init for details of how it's set up
